### ISSUE TITLE
Ability to export to CSV/JSON

### ISSUE THREAD

**Issue by dend** [nat/keyrace#30]
Content is already stored internally - would be neat to export to CSV/JSON for further historical analysis (e.g. in a Jupyter notebook).

**Happy to contribute with a pull request** and use this issue as a tracking item, but want to make sure I am not stepping on anyone's toes if this is already planned.

**Comment by nat** [comment]
Do ~/.keyrace.minutes.tmp and ~/.keyrace.histogram.tmp do the trick?

**Comment by dend** [comment]
Partially. In their raw state, it might be hard to work without some context. I think of two ways to make those usable:

1. **Documenting the format.** Right now it's just a comma-separated list of values without context. I could add some notes in the `README` that outline how the values are structured. In this case, the re-use of this data is left as an exercise to the reader.
2. **Have en experimental approach to have a more rich CSV/JSON format as an export option.** It would make it more convenient to analyze the data outside of `keyrace`, but it adds a new code path to generate whatever useful file formats are available for export.

I don't know how many other people other than myself need the export option, so I am happy to start with (1) and add a bit content to the `README` describing the format before jumping to implementing more complexity. 😃

**Comment by nat** [comment]
Given #31, some export option may be desirable. Maybe even a way to easily populate a spreadsheet.

**Comment by dend** [comment]
@nat 100%. So, something like:

`Export...` >
    > `CSV`
    > `JSON`
    > `Copy to clipboard`

Happy to get to work on this once @jessfraz's PR is merged.

**Comment by dend** [comment]
@nat @jessfraz I see that #35 is merged - worth for me picking up the export work?
